services:
  skillfresh:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=skillfresh
      - POSTGRES_USER=skillfresh
      - POSTGRES_DB=skillfresh

  strapi-crm-test:
    image: postgres:14-alpine
    ports:
      - 54321:5432
    volumes:
      - ~/apps/postgres2:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=skillfresh-test
      - POSTGRES_USER=skillfresh-test
      - POSTGRES_DB=skillfresh-test

  adminer:
    image: adminer
    ports:
      - 7777:8080
    environment:
      ADMINER_DEFAULT_SERVER: skillfresh
    depends_on:
      - skillfresh
